parameters:
    sidus_filter.filter.type.date_range.class: Sidus\EAVFilterBundle\Filter\Type\DateRangeFilterType
    sidus_filter.filter.type.text.class: Sidus\EAVFilterBundle\Filter\Type\TextFilterType
    sidus_filter.filter.type.choice.class: Sidus\EAVFilterBundle\Filter\Type\ChoiceFilterType
    sidus_eav_filter.filter.type.autocomplete_data.class: Sidus\EAVFilterBundle\Filter\Type\AutocompleteDataFilterType

services:
    sidus_eav_filter.filter.type.autocomplete_data:
        class: '%sidus_eav_filter.filter.type.autocomplete_data.class%'
        arguments:
            - autocomplete_data
            - 'Sidus\EAVBootstrapBundle\Form\Type\AutocompleteDataSelectorType'
        tags:
            - { name: sidus.filter_type }
