parameters:
    sidus_filter.filter.class: Sidus\EAVFilterBundle\Filter\ElasticaFilter
    sidus_eav_filter.configuration.class: Sidus\EAVFilterBundle\Configuration\EAVElasticaFilterConfigurationHandler
    sidus_eav_filter.elastica.data_value_subscriber.class: Sidus\EAVFilterBundle\Events\DataValuesSubscriber

services:
    sidus_eav_filter.elastica.data_value_subscriber:
        class: "%sidus_eav_filter.elastica.data_value_subscriber.class%"
        arguments: ['@doctrine']
        tags:
            - { name: kernel.event_subscriber }
