services:
    Sidus\FilterBundle\Factory\QueryHandlerFactoryInterface:
        alias: Sidus\EAVFilterBundle\Factory\EAVQueryHandlerFactory

    Sidus\EAVFilterBundle\Factory\EAVQueryHandlerFactory:
        public: false
        autowire: true
        tags:
            - { name: sidus.query_handler_factory }
