services:
    sidus_eav_filter.factory.query_handler:
        class: Sidus\EAVFilterBundle\Factory\EAVQueryHandlerFactory
        arguments:
            - '@sidus_filter.registry.filter_type'
            - '@doctrine'
            - '@sidus_eav_model.family.registry'
            - '@sidus_eav_filter.helper.eav_filter'
        tags:
            - { name: sidus.query_handler_factory }
