services:
    Sidus\FilterBundle\Factory\QueryHandlerFactoryInterface:
        alias: Sidus\EAVFilterBundle\Factory\EAVQueryHandlerFactory

    Sidus\EAVFilterBundle\Factory\EAVQueryHandlerFactory:
        public: false
        arguments:
            - '@Sidus\FilterBundle\Registry\FilterTypeRegistry'
            - '@sidus_eav_model.entity_manager'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@Sidus\EAVFilterBundle\Filter\EAVFilterHelper'
            - '@Sidus\EAVModelBundle\Doctrine\DataLoaderInterface'
        tags:
            - { name: sidus.query_handler_factory }
