services:
    sidus_eav_filter.filter.type.autocomplete_data:
        class: Sidus\EAVFilterBundle\Filter\Type\AutocompleteDataFilterType
        arguments:
            - autocomplete_data
            - Sidus\EAVBootstrapBundle\Form\Type\AutocompleteDataSelectorType
        tags:
            - { name: sidus.filter_type }

    sidus_eav_filter.filter.type.date_range:
        class: Sidus\EAVFilterBundle\Filter\Type\DateRangeFilterType
        arguments:
            - date_range
            - Sidus\FilterBundle\Form\Type\DateRangeType
        tags:
            - { name: sidus.filter_type }

    sidus_eav_filter.filter.type.text:
        class: Sidus\EAVFilterBundle\Filter\Type\TextFilterType
        arguments:
            - text
            - Symfony\Component\Form\Extension\Core\Type\TextType
        tags:
            - { name: sidus.filter_type }

    sidus_eav_filter.filter.type.choice:
        class: Sidus\EAVFilterBundle\Filter\Type\ChoiceFilterType
        arguments:
            - choice
            - Symfony\Component\Form\Extension\Core\Type\ChoiceType
        calls:
            - [setDoctrine, ['@doctrine']]
        tags:
            - { name: sidus.filter_type }
