services:
    Sidus\EAVFilterBundle\Filter\Type\AutocompleteDataFilterType:
        public: false
        arguments:
            - autocomplete_data
            - Sidus\EAVBootstrapBundle\Form\Type\AutocompleteDataSelectorType
        tags:
            - { name: sidus.filter_type }

    Sidus\EAVFilterBundle\Filter\Type\DateRangeFilterType:
        public: false
        arguments:
            - date_range
            - Sidus\FilterBundle\Form\Type\DateRangeType
        calls:
            - [setFallbackFilterType, ['@Sidus\FilterBundle\Filter\Type\Doctrine\DateRangeFilterType']]
        tags:
            - { name: sidus.filter_type }

    Sidus\EAVFilterBundle\Filter\Type\TextFilterType:
        public: false
        arguments:
            - text
            - Symfony\Component\Form\Extension\Core\Type\TextType
        calls:
            - [setFallbackFilterType, ['@Sidus\FilterBundle\Filter\Type\Doctrine\TextFilterType']]
        tags:
            - { name: sidus.filter_type }

    Sidus\EAVFilterBundle\Filter\Type\ChoiceFilterType:
        public: false
        arguments:
            - choice
            - Symfony\Component\Form\Extension\Core\Type\ChoiceType
        calls:
            - [setDoctrine, ['@Doctrine\Common\Persistence\ManagerRegistry']]
            - [setFallbackFilterType, ['@Sidus\FilterBundle\Filter\Type\Doctrine\ChoiceFilterType']]
        tags:
            - { name: sidus.filter_type }
